[build]
buildCommand = "npm install --include=dev && npm run build && npx prisma generate"

[deploy]
startCommand = "sh startup.sh"
healthcheckPath = "/health"
restartPolicyType = "always"
numReplicas = 1
